// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserRegistrationAPI;

namespace UserRegistrationAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserRegistrationAPI.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Apartanemt")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("House")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9245fe4a-d402-451c-b9ed-9c1a04247482"),
                            Apartanemt = 10,
                            City = "Vilnius",
                            House = 10,
                            Street = "Neries g."
                        },
                        new
                        {
                            Id = new Guid("083a8133-231d-4028-a878-b365ba2f9eb4"),
                            Apartanemt = 20,
                            City = "Kaunas",
                            House = 20,
                            Street = "Nemuno g."
                        });
                });

            modelBuilder.Entity("UserRegistrationAPI.Models.InfoSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PersonalNumber")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("InfoSheets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9245fe4a-d402-451c-b9ed-9c1a04247482"),
                            AddressId = new Guid("9245fe4a-d402-451c-b9ed-9c1a04247482"),
                            Email = "vardenis@vardenis.lt",
                            FirstName = "Vardenis",
                            LastName = "Pavarednis",
                            PersonalNumber = 38989521245.0
                        },
                        new
                        {
                            Id = new Guid("083a8133-231d-4028-a878-b365ba2f9eb4"),
                            AddressId = new Guid("083a8133-231d-4028-a878-b365ba2f9eb4"),
                            Email = "antanas@antanas.lt",
                            FirstName = "Antanas",
                            LastName = "Antanaitis",
                            PersonalNumber = 38989521245.0
                        });
                });

            modelBuilder.Entity("UserRegistrationAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InfoSheetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InfoSheetId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("991ff595-0174-4011-87b3-bd968202b075"),
                            InfoSheetId = new Guid("9245fe4a-d402-451c-b9ed-9c1a04247482"),
                            Password = "P@ssword1",
                            Role = "User",
                            Username = "Vardenis"
                        },
                        new
                        {
                            Id = new Guid("256e4f68-a17b-4a39-ac29-653d977c8883"),
                            InfoSheetId = new Guid("083a8133-231d-4028-a878-b365ba2f9eb4"),
                            Password = "P@ssword2",
                            Role = "User",
                            Username = "Antanas"
                        });
                });

            modelBuilder.Entity("UserRegistrationAPI.Models.InfoSheet", b =>
                {
                    b.HasOne("UserRegistrationAPI.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("UserRegistrationAPI.Models.User", b =>
                {
                    b.HasOne("UserRegistrationAPI.Models.InfoSheet", "InfoSheet")
                        .WithMany()
                        .HasForeignKey("InfoSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InfoSheet");
                });
#pragma warning restore 612, 618
        }
    }
}
